services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/sites/:/etc/nginx/sites-available
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
    ports:
      - "8000:80"
      - "8443:443"
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./:/var/www/html:cached
    depends_on:
      - mariadb
    environment:
      NETTE_DEBUG: 1
      PHP_EXTENSION_MYSQLI: 1
#      STARTUP_COMMAND_1: composer install
#      STARTUP_COMMAND_2: NETTE_DEBUG=1 php bin/console migrations:migrate --no-interaction
#      STARTUP_COMMAND_3: NETTE_DEBUG=1 php bin/console doctrine:fixtures:load --no-interaction

  mariadb:
    image: mariadb:10.4
    environment:
      - MARIADB_ROOT_PASSWORD=contributte
      - MARIADB_PASSWORD=contributte
      - MARIADB_USER=contributte
      - MARIADB_DATABASE=contributte
    volumes:
      - ./db/entrypoint:/docker-entrypoint-initdb.d
#      - .docker/data/mysql:/var/lib/mysql
    ports:
      - 3306:3306