services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/sites/:/etc/nginx/sites-available
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
    ports:
      - "8000:80"
      - "8443:443"
    stop_grace_period: 2s

  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./:/var/www/html:cached
    depends_on:
      redis:
        condition: service_started
      mariadb:
        condition: service_healthy
    stop_grace_period: 2s
    environment:
      NETTE_DEBUG: 1
      STARTUP_COMMAND_1: php bin/console migrations:migrate --no-interaction

  mariadb:
    image: mariadb:10.4
    environment:
      - MARIADB_ROOT_PASSWORD=contributte
      - MARIADB_PASSWORD=contributte
      - MARIADB_USER=contributte
      - MARIADB_DATABASE=contributte
    ports:
      - 3306:3306
    stop_grace_period: 2s
    healthcheck:
      test: ["CMD", "mysql", "-ucontributte", "-pcontributte", "-Dcontributte", "-e", "SELECT 1"]
      interval: 2s
      retries: 10
      start_period: 2s
      timeout: 2s

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
